name: Terraform-Validate-Plan-Apply

on:
  workflow_call:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*


permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  terraform:
    name: 'Terraform Action'
    runs-on: ubuntu-latest

    permissions:
      pull-requests: 'write'
      contents: read
      id-token: write

    steps:
      - name: 'Trigger Terraform Validate and Action Build'
        run: |-
          ls -ltr && pwd
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          echo "GITHUB_ACTIONS: $GITHUB_ACTIONS"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          if [ ${{ github.event_name == 'pull_request' }} ]; then
            echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
            echo "GITHUB PULL REQUEST: ${{ github.event.pull_request.number }}"
            echo "_GIT_HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}"
            echo "_GIT_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}"
          else
            echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
            echo "GITHUB BRANCH: ${{ github.ref }}"
          fi

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"




